[package]
name = "desk"
version = "0.1.0"
authors = ["Andrzej Klajnert <github@aklajnert.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
idasen = { git = "https://github.com/aklajnert/idasen.git" }
toml = "0.5.6"
serde = { version = "1.0", features = ["derive"] }